const SUPABASE_URL='https://woanvjetrqpmudfuwsou.supabase.co';
const SUPABASE_KEY='sb_publishable_LWVa2TIARXNsnQHwRy1GyQ_u71Pe76h';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const WA='213561716497';
function wa(msg='Bonjour DIGITAL DZ, je souhaite avoir des informations sur la formation.'){window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(msg),'_blank')}
function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2800)}
async function user(){const {data:{user}}=await sb.auth.getUser();return user}
async function profile(){const u=await user();if(!u)return null;const {data,error}=await sb.from('client_profiles').select('*').eq('id',u.id).maybeSingle();if(error)console.warn(error);return data}
async function requireAccess(){const u=await user();if(!u){location.href='connexion.html';return null}const p=await profile();if(!p||!p.access_active){location.href='connexion.html?activate=1';return null}return {u,p}}
async function logout(){await sb.auth.signOut();location.href='connexion.html'}
function nav(active){document.querySelectorAll('.nav[data-page]').forEach(a=>{if(a.dataset.page===active)a.classList.add('active')})}
function shell(active){document.body.insertAdjacentHTML('afterbegin',`<div class="top"><div><div class="logo">DIGITAL <span>DZ</span></div><div class="tag">Apprendre • Créer • Vendre • Progresser</div></div><div class="search"><input placeholder="🔎 Rechercher un module, une leçon, un test..." onkeydown="if(event.key==='Enter') location.href='modules.html?q='+encodeURIComponent(this.value)"></div><div class="user"><div class="avatar">👤</div><span id="topEmail">Apprenant</span><button class="btn secondary" onclick="logout()">Déconnexion</button></div></div><div class="layout"><aside class="side"><div class="side-title">Mon espace</div><a class="nav" data-page="dashboard" href="dashboard.html">🏠 Accueil</a><a class="nav" data-page="parcours" href="dashboard.html#parcours">📊 Mon parcours</a><a class="nav" data-page="modules" href="modules.html">📚 28 Modules</a><a class="nav" data-page="tests" href="tests.html">📝 160 Tests</a><a class="nav" data-page="missions" href="missions.html">🎯 Missions pratiques</a><a class="nav" data-page="challenge" href="missions.html#challenge">🔥 Challenge 30 jours</a><a class="nav" data-page="progression" href="progression.html">📈 Ma progression</a><a class="nav" data-page="badges" href="progression.html#badges">🏆 Badges & Récompenses</a><a class="nav" data-page="attestation" href="attestation.html">🎓 Attestation</a><div class="side-title">Ressources</div><a class="nav" data-page="videos" href="ressources-client.html#videos">🎥 Vidéos & tutoriels</a><a class="nav" data-page="resources" href="ressources-client.html">📥 Ressources</a><a class="nav" data-page="favorites" href="progression.html#favoris">❤️ Favoris</a><a class="nav" data-page="tools" href="ressources-client.html#tools">🤖 Outils & IA</a><a class="nav" data-page="support" href="support.html">💬 Support WhatsApp</a><div class="side-title">Compte</div><a class="nav" data-page="order" href="commande.html">🛒 Commande / Paiement</a><a class="nav" data-page="profile" href="profil.html">👤 Mon profil</a></aside><main class="main"><div id="toast" class="toast"></div>`);nav(active)}
function closeShell(){document.querySelector('.main')?.insertAdjacentHTML('beforeend','</main></div><a class="wa" href="#" onclick="wa();return false">💬 WhatsApp</a>')}
async function fillUser(){const u=await user();if(u){const e=document.getElementById('topEmail');if(e)e.textContent=u.email||'Apprenant'}}
async function activateCode(code){const {data,error}=await sb.rpc('activate_access_code',{p_code:code.trim().toUpperCase()});if(error)throw error;return data}
